import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/banner'
import NavBar from '@/components/navbar'
import { CardSize } from '@/enums/card-size'
import SectionCard from '@/components/section-cards'
import { IVideoResponse } from '@/interfaces/ivideoResponse'
import { getPopularVideos, getVideos } from '@/services/video.service'

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailers");
  const productivityVideos = await getVideos("day in life of software engineer meta");
  const travelVideos = await getVideos("netflix trailers");
  const popularVideos = await getPopularVideos();
  return { props: { disneyVideos, productivityVideos, travelVideos, popularVideos } }
}
interface IServerSideProps {
  disneyVideos: Array<IVideoResponse>;
  productivityVideos: Array<IVideoResponse>;
  travelVideos: Array<IVideoResponse>;
  popularVideos: Array<IVideoResponse>;
}
export default function Home(props: IServerSideProps) {

  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <NavBar />
        <Banner
          title='Social Network'
          subtitle='the creation of facebook by Mark Zuckemberg'
          imageUrl='/images/socialnetworkimage.jpg'
          videoId='lB95KLmpLR4'
        />
        <div className={styles.sectionWrapper}>
          <SectionCard title='Disney' videos={props.disneyVideos as Array<IVideoResponse>} size={CardSize.LARGE} />
          <SectionCard title='Travel' videos={props.travelVideos as Array<IVideoResponse>} size={CardSize.SMALL} />
          <SectionCard title='Productivity' videos={props.productivityVideos as Array<IVideoResponse>} size={CardSize.MEDIUM} />
          <SectionCard title='Populars' videos={props.popularVideos as Array<IVideoResponse>} size={CardSize.SMALL} />
        </div>
      </div>
    </div>
  )
}
